language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm test
  - cd coffee-example && npm install
  - cd coffee-example && npm run coffee
  - cd coffee-example && DEBUG=locha npm test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
